name: Test plugin

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "ci/*"

jobs:
  Test-plugin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { image: qgis/qgis, tag: release-3_34 }
          - { image: ghcr.io/qgis/qgis-qt6-unstable, tag: main }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export requirements.txt
        run: |
          pip3 install uv
          uv export -o requirements.txt --no-dev --no-hashes

      - name: Docker pull and create qgis-testing-environment
        run: |
          docker pull ${{ matrix.config.tag }}:${{ matrix.config.tag }}
          docker run -d --name qgis-testing-environment -v .:/tests_directory/plugin_dir -e DISPLAY=:99 ${{ matrix.config.image }}:${{ matrix.config.tag }}

      - name: Docker set up QGIS
        run: |
          docker exec qgis-testing-environment sh -c "qgis_setup.sh plugin_dir"
          docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/plugin_dir"
          docker exec qgis-testing-environment sh -c "ln -s /tests_directory/plugin_dir /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/plugin_dir"
          docker exec qgis-testing-environment sh -c "pip3 install -r /tests_directory/plugin_dir/requirements.txt"

      - name: Docker run plugin tests
        run: |
          docker exec qgis-testing-environment sh -c "qgis_testrunner.sh plugin_dir.test_suite.test_package"
